[package]

name = "server"
version = "0.0.1"
authors = ["Nathaniel Theis <nttheis@gmail.com>"]

[dependencies.shared]
path = "../shared"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"
