[package]

name = "shared"
version = "0.0.1"
authors = ["Nathaniel Theis <nttheis@gmail.com>"]

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"

[dependencies.anymap]
git = "https://github.com/chris-morgan/anymap"


